### ISSUE TITLE
do you have code example for many dimensions for multivariate functions

### ISSUE THREAD

**Issue by Sandy4321** [GuillaumeStaermanML/FIF#2]
do you have code example for many dimensions for multivariate functions
as written in paper?
5 Extension of FIF
Extension to multivariate functions FIF can be easily extended to the multivariate
functional data, i.e. when the quantity of interest lies in Rd for each moment of time. For
this, the coordinate-wise sum of the d corresponding scalar products is used to project
the data onto a chosen dictionary element:

**Comment by GuillaumeStaermanML** [comment]
Examples are provided in the notebook at https://github.com/Gstaerman/FIF/tree/master/Code_FIF/Section_5

**Comment by GuillaumeStaermanML** [comment]
You'll find a bivariate example with MNIST dataset where numbers are transformed into bivariate functions. One from anomaly detection and one from classification as mentionned in  https://arxiv.org/pdf/1904.04573.pdf (at the end of the supplementary material).

**Comment by katkaf** [comment]
Hello Guillaume,
link to multivariate example mentioned above doesn't work, do you have some other example? Could you please clarify what should be data input in case of multivariate data? 
Thanks a lot!

**Comment by GuillaumeStaermanML** [comment]
Hey katkaf,

the new link is https://github.com/GuillaumeStaermanML/FIF/tree/master/MFIF_python/Section_5 
The code for FIF in the univariate case has been recently updated with cython/c++ code in order to accelerate the computation time. However, the Multivariate FIF (MFIF) code is still in python and is available to the aforementioned link.
